### ISSUE TITLE
Minimal test faild, pdftex.map can't download 

### ISSUE THREAD

**Issue by MIracleyin** [let-def/texpresso#38]
[info] working directory: /Users/projects/personal/texpresso
[info] executable path: /Users/projects/personal/texpresso/build/texpresso
[info] document path: /Users/projects/personal/texpresso/test
[info] document name: simple.tex
texpresso logo: 512x512
[info] tectonic path: /Users/yin/projects/personal/texpresso/build/texpresso-tonic
[dvi] loading pdftex.map
note: "version 2" Tectonic command-line interface activated
note: not in a document workspace; using the built-in default bundle
note: downloading SHA256SUM
note: downloading pdftex.map
warning: failure downloading "pdftex.map" from network
caused by: error decoding response body: operation timed out
caused by: operation timed out

**Comment by let-def** [comment]
TeXpresso uses [Tectonic](https://github.com/tectonic-typesetting/tectonic) as a LaTeX distribution.
It fetches LaTeX files as needed, so there is no big installation upfront, but it needs an internet connection the first time a package is used.

I don't know how to troubleshoot this connection problem, but TeXpresso should work exactly like Tectonic. Removing TeXpresso from the equation should make things easier to diagnose: try to get Tectonic to work, and check their issues/forum, someone probably encountered this problem.

**Comment by let-def** [comment]
If you cannot directly access the internet, you can use a proxy with the `https_proxy`/`http_proxy` environment variables.
