### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by QuChunhe** [let-def/texpresso#41]
22.04.1-Ubuntu SMP PREEMPT_DYNAMIC   2 x86_64 x86_64 x86_64 GNU/Linux
```shell
make config
make clean  texpresso
```

error message

> rm -rf build/objects/*
make -C src texpresso
make[1]: Entering directory '/home/quchunhe/Git/texpresso/src'
gcc -O2 -ggdb -I. -fPIC -c -o ../build/objects/driver.o -Idvi/ driver.c
gcc -O2 -ggdb -I. -fPIC -c -o ../build/objects/main.o -Idvi/ main.c
main.c:795:1: error: static declaration of ‘SDL_SetWindowAlwaysOnTop’ follows non-static declaration
  795 | SDL_SetWindowAlwaysOnTop(SDL_Window *window, SDL_bool state)
      | ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/SDL2/SDL_events.h:33,
                 from /usr/include/SDL2/SDL.h:41,
                 from main.c:25:
/usr/include/SDL2/SDL_video.h:1123:30: note: previous declaration of ‘SDL_SetWindowAlwaysOnTop’ with type ‘void(SDL_Window *, SDL_bool)’
 1123 | extern DECLSPEC void SDLCALL SDL_SetWindowAlwaysOnTop(SDL_Window * window,
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:34: ../build/objects/main.o] Error 1
make[1]: Leaving directory '/home/quchunhe/Git/texpresso/src'
make: *** [Makefile:8: texpresso] Error 2

**Comment by let-def** [comment]
Thanks for the report. I hop the last commit fixed the bug.

**Comment by let-def** [comment]
Fixed.
