### ISSUE TITLE
missing dependencies in Ubuntu install instructions

### ISSUE THREAD

**Issue by samvang** [let-def/texpresso#47]
While trying to install this on Ubuntu 22.04.4 LTS, I was missing dependencies `leptonica` and `harfbuzz` and it was not so clear to me from the instructions that I would need to install them, and how.
Do you want to add the packages `libleptonica-dev` and `libharfbuzz-dev` to [this line](https://github.com/let-def/texpresso/blob/defeab4638143d3448d00619eff26a1c5ef1738a/INSTALL.md?plain=1#L26)  ?

**Comment by samvang** [comment]
Oh, I just noticed that `libharfbuzz-dev` is mentioned just below that line for Ubuntu 20, so for that package my comment is that I needed it also on Ubuntu 22

**Comment by let-def** [comment]
Thanks for the report.
Interestingly, a few weeks ago I got the build to work on a freshly installed Ubuntu 22.04 with the previous instructions.
I updated with your suggestions anyway, it is hard to control the precise build environment.
