### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by JalenLv** [let-def/texpresso#53]
Hi! I am using Ubuntu22.04 and failed to run the testing document. And here is my guess:

The first time I tried building the project, I found myself missing `tesseract`:
```sh
...
make[2]: Entering directory '/home/jalenlv/Downloads/texpresso'
mkdir -p build/objects
echo >Makefile.config "CFLAGS=-O2 -ggdb -I. -fPIC"
echo >>Makefile.config 'CC=gcc $(CFLAGS)'
echo >>Makefile.config 'LDCC=g++ $(CFLAGS)'
echo >>Makefile.config "LIBS=-lmupdf -lm `CC=gcc ./mupdf-config.sh` -lz -ljpeg -ljbig2dec -lharfbuzz -lfreetype -lopenjp2 -lgumbo -lSDL2"
/usr/bin/ld: cannot find -ltesseract: No such file or directory
collect2: error: ld returned 1 exit status
echo >>Makefile.config "TECTONIC_ENV="
make[2]: Leaving directory '/home/jalenlv/Downloads/texpresso'
gcc -O2 -ggdb -I. -fPIC -c -o ../build/objects/driver.o -Idvi/ driver.c
gcc -O2 -ggdb -I. -fPIC -c -o ../build/objects/main.o -Idvi/ main.c
...
```

Even after I installed `tesseract` using `sudo apt install tesseract-ocr libtesseract-dev` and re-cloned the repo, I still failed to run the testing doc. When I tried the testing doc, I got
```sh
[info] working directory: /home/jalenlv/Downloads/texpresso
[info] executable path: /home/jalenlv/Downloads/texpresso/build/texpresso
[info] document path: /home/jalenlv/Downloads/texpresso/test
[info] document name: simple.tex
texpresso logo: 512x512
[info] tectonic path: texpresso-tonic
[dvi] loading pdftex.map
bundle_serve_hooks_cat: cannot read answer
[dvi] loading kanjix.map

```
and the window just popped up and shut down immediately. This was the same both with and without `tessetact` installed.

Many thanks if you can help out!

**Comment by JalenLv** [comment]
It was awkward that when I `make clean` and then `make`, I managed to install the project properly. That's weird though.

**Comment by let-def** [comment]
The missing tesseract was probably not the problem: the config script tries to link tesseract just to guess the system configuration, it should not affect the rest of the build process.
The `bundle_serve_hooks_cat: cannot read answer` line is a more serious problem: on first try, TeXpresso uses Tectonic to download TeX dependencies on demand. In your case, it seemed it crashed for one reason or another in the first few runs.
I will try to log more information in the future.

**Comment by let-def** [comment]
You can try running `build/texpresso-tonic -X bundle serve` to see what happens.

Just for the record, I got a similar behavior as what you described on macOS by:
- launching texpresso on some tex file and keeping it running in the background
- building a new version, the important point is that a new `texpresso-tonic` binary is produced
- the new binary cannot be launched as long as the previous one is running

The crash happens at very low-level (`exec` syscall failing), so the kernel is involved somewhere. However if I rename the binary, it works.

The problem on Ubuntu is probably different, but the output produced by running the command should be informative.
If everything works well, the command should print:
```
note: "version 2" Tectonic command-line interface activated
note: not in a document workspace; using the built-in default bundle
```
and wait for user input (you can close it with Ctrl-D or Ctrl-C if you reach this point).

**Comment by JalenLv** [comment]
Since I have properly built it, I got the expected output. I am closing the issue if there isn't anything I can help with.

BTW, I want to know if you are interested in adding Chinese support for the neovim plugin. The SyncTeX backward functionality won't work properly if there is any Chinese character in the path. If so when I click on some text, TeXpresso sends back a path like this
![image](https://github.com/let-def/texpresso/assets/141929488/beca85fc-8e3e-4e01-b948-04f728097965)

**Comment by let-def** [comment]
Thank for reporting the issue. PR #56 should fix this problem.

**Comment by let-def** [comment]
(I tested locally and it seems fine, tell me if it works for you and I will merge it)

**Comment by JalenLv** [comment]
It works!

Many thanks. I am so impressed by your prompt replies and the project is nice.

**Comment by JalenLv** [comment]
I tried building the project on macOS and I got this
```sh
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It seemed that I lacked a bunch of dependencies and after I installed `tesseract`, `mujs`, and `gumbo-parser`, `make` was successful.

Similarly, I had the same problem as the one on Ubuntu. I had to `make clean` and `make`, and then Tectonic started downloading things properly.

Is this a common phenomenon? I think it's good to add some instructions in the `INSTALL.md` file concerning those scenarios, i.e., the `make clean` and then `make` and dependencies on macOS.

**Comment by let-def** [comment]
The configuration is done lazily during the first invocation to make. Running `make config` forces the build system to recheck dependencies, that's probably what you are looking for in your case.

But you are right that this should be automated, I am thinking to add a `build.sh` script that takes care of that.
However I have no time to work on that for the moment. Thanks for the feedback (I hope you managed to get everything to work as you expected in the end).

**Comment by JalenLv** [comment]
Appreciate it. Everything works perfectly for now.

Many thanks again and I am closing the issue.
