### ISSUE TITLE
Error SDL could not initialize wayland driver when running it

### ISSUE THREAD

**Issue by sambaPython24** [let-def/texpresso#69]
I am trying to install texpresso on Ubuntu 23.04
```
Description:	Ubuntu 23.04
Release:	23.04
```
when running ```build/texpresso test/simple.tex``` I get the error 

```
[info] working directory: <mypath>/texpresso
[info] executable path: <mypath>/texpresso/build/texpresso
[info] document path: <mypath>/texpresso/test
[info] document name: simple.tex
SDL could not initialize wayland driver! SDL_Error: wayland not available
Falling back to default driver
texpresso logo: 512x512
[info] tectonic path: texpresso-tonic
[dvi] loading pdftex.map
bundle_serve_hooks_cat: cannot read answer
[dvi] loading kanjix.map
```

**Comment by mathlab08** [comment]
Please use Ubuntu-24.04
https://www.mediafire.com/file/3wowa4xas2jruff/Ubuntu-24.04.tar/file

**Comment by let-def** [comment]
I don't know if Ubuntu version is the problem; it is sure to work with 24.04, but 23.04 might be fine too.

However, there is no problem with the log you shared: TeXpresso tries Wayland first and then falls back to X11.

**Comment by sambaPython24** [comment]
But in the end, opening the GUI fails even with X11. A window opens and closes immediately after that when I run the suggested command. 
And I don't know, howto debug this error, since I canot find the error ```bundle_serve_hooks_cat: cannot read answer```.
